#pragma once

namespace OBJ
{
	enum ID { OBJ_TERRAIN,OBJ_SUMMON, OBJ_MONSTER,OBJ_MONSTER_ATTACK, OBJ_EFFECT,OBJ_PLAYER, OBJ_PLAYER_AD_ATTACK, OBJ_PLAYER_AP_ATTACK,OBJ_PORTAL, OBJ_DAMAGE, OBJ_STATUS, OBJ_UI,OBJ_BUTTON,OBJ_MOUSE, OBJ_END };

}

namespace MONSTER {
	enum ID {
		BLUEWOLF,
		END
	};
	enum STATE {
		MONSTER_IDLE,
		MONSTER_DIE
	};

}